[package]
edition = "2021"
name = "minesweeper-cmd-game"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minesweeper-solver = {path = "../minesweeper-solver"}
